version: "3.8"
services:
  api:
    image: tiunovnn/hse-knee-api:v2
    environment:
      - API_S3_ACCESS_KEY_ID=
      - API_S3_BUCKET=
      - API_S3_SECRET_ACCESS_KEY=
    ports:
      - 80:80
    restart: always
